services:
  - type: web
    name: airport-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn airport_bot:app"
    plan: free
    regions:
      - oregon

