
services:
  - type: web
    name: telegram-airport-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python airport_bot.py
    envVars:
      - key: 8051795674:AAHuqYMmC47CzFsd-Li-y0_kEH3bSZi01Uk
        sync: false
      - key: 861b70e5357b042f9c72c5d242e24021
        sync: false
