services:
  - type: web
    name: airport-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn airport_bot:app"
    plan: free
    regions:
      - oregon
    envVars:
      - key: TOKEN
        value: 8051795674:AAHuqYMmC47CzFsd-Li-y0_kEH3bSZi01Uk
      - key: API_KEY
        value: ac2469df44587ed7b51f78729f69bd30
