
services:
  - type: web
    name: telegram-airport-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python airport_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: AVIATIONSTACK_API_KEY
        sync: false
